### ISSUE TITLE
Tests fail when RabbitMQ is not present

### ISSUE THREAD

**Issue by rpignolet** [roboconf/roboconf-platform#159]
````
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.roboconf.messaging.internal.RabbitMqTestUtilsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in net.roboconf.messaging.internal.RabbitMqTestUtilsTest
Running net.roboconf.messaging.internal.client.rabbitmq.DmClientTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.104 sec - in net.roboconf.messaging.internal.client.rabbitmq.DmClientTest
Running net.roboconf.messaging.internal.client.rabbitmq.AgentClientTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.043 sec - in net.roboconf.messaging.internal.client.rabbitmq.AgentClientTest
Running net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest
Tests run: 10, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 0.263 sec <<< FAILURE! - in net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest
testExchangesBetweenTheDmAndOneAgent(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.051 sec  <<< ERROR!
org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>
	at org.junit.Assume.assumeThat(Assume.java:70)
	at org.junit.Assume.assumeTrue(Assume.java:39)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExchangesBetweenTheDmAndOneAgent(RabbitMqTest.java:72)

testExchangesBetweenTheDmAndOneAgent(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.053 sec  <<< ERROR!
com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:338)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:590)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:612)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqClientDm.openConnection(RabbitMqClientDm.java:111)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.cleanRabbitMq(RabbitMqTest.java:61)

testExchangesBetweenTheDmAndThreeAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.039 sec  <<< ERROR!
org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>
	at org.junit.Assume.assumeThat(Assume.java:70)
	at org.junit.Assume.assumeTrue(Assume.java:39)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExchangesBetweenTheDmAndThreeAgents(RabbitMqTest.java:80)

testExchangesBetweenTheDmAndThreeAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.04 sec  <<< ERROR!
com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:338)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:590)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:612)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqClientDm.openConnection(RabbitMqClientDm.java:111)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.cleanRabbitMq(RabbitMqTest.java:61)

testExportsBetweenAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.043 sec  <<< ERROR!
org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>
	at org.junit.Assume.assumeThat(Assume.java:70)
	at org.junit.Assume.assumeTrue(Assume.java:39)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExportsBetweenAgents(RabbitMqTest.java:88)

testExportsBetweenAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.044 sec  <<< ERROR!
com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:338)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:590)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:612)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqClientDm.openConnection(RabbitMqClientDm.java:111)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.cleanRabbitMq(RabbitMqTest.java:61)

testExportsRequestsBetweenAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.043 sec  <<< ERROR!
org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>
	at org.junit.Assume.assumeThat(Assume.java:70)
	at org.junit.Assume.assumeTrue(Assume.java:39)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExportsRequestsBetweenAgents(RabbitMqTest.java:96)

testExportsRequestsBetweenAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.044 sec  <<< ERROR!
com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:338)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:590)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:612)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqClientDm.openConnection(RabbitMqClientDm.java:111)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.cleanRabbitMq(RabbitMqTest.java:61)

testExportsBetweenSiblingAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.039 sec  <<< ERROR!
org.junit.internal.AssumptionViolatedException: got: <false>, expected: is <true>
	at org.junit.Assume.assumeThat(Assume.java:70)
	at org.junit.Assume.assumeTrue(Assume.java:39)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExportsBetweenSiblingAgents(RabbitMqTest.java:104)

testExportsBetweenSiblingAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)  Time elapsed: 0.04 sec  <<< ERROR!
com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:338)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:590)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:612)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqClientDm.openConnection(RabbitMqClientDm.java:111)
	at net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.cleanRabbitMq(RabbitMqTest.java:61)

Running net.roboconf.messaging.internal.client.dismiss.DismissClientsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in net.roboconf.messaging.internal.client.dismiss.DismissClientsTest
Running net.roboconf.messaging.internal.client.MessageServerClientFactoryTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in net.roboconf.messaging.internal.client.MessageServerClientFactoryTest
Running net.roboconf.messaging.internal.client.test.TestClientAgentTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec - in net.roboconf.messaging.internal.client.test.TestClientAgentTest
Running net.roboconf.messaging.internal.client.test.TestClientDmTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in net.roboconf.messaging.internal.client.test.TestClientDmTest
Running net.roboconf.messaging.internal.utils.RabbitMqUtilsTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.046 sec - in net.roboconf.messaging.internal.utils.RabbitMqUtilsTest
Running net.roboconf.messaging.internal.utils.SerializationUtilsTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec - in net.roboconf.messaging.internal.utils.SerializationUtilsTest
Running net.roboconf.messaging.reconfigurables.ReconfigurableClientTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in net.roboconf.messaging.reconfigurables.ReconfigurableClientTest
Running net.roboconf.messaging.processors.AbstractMessageProcessorTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.804 sec - in net.roboconf.messaging.processors.AbstractMessageProcessorTest

Results :


Tests in error: 
net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExchangesBetweenTheDmAndOneAgent(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)
  Run 1: RabbitMqTest.testExchangesBetweenTheDmAndOneAgent:72 » AssumptionViolated got:...
  Run 2: RabbitMqTest.cleanRabbitMq:61 » AuthenticationFailure ACCESS_REFUSED - Login w...

net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExchangesBetweenTheDmAndThreeAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)
  Run 1: RabbitMqTest.testExchangesBetweenTheDmAndThreeAgents:80 » AssumptionViolated g...
  Run 2: RabbitMqTest.cleanRabbitMq:61 » AuthenticationFailure ACCESS_REFUSED - Login w...

net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExportsBetweenAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)
  Run 1: RabbitMqTest.testExportsBetweenAgents:88 » AssumptionViolated got: <false>, ex...
  Run 2: RabbitMqTest.cleanRabbitMq:61 » AuthenticationFailure ACCESS_REFUSED - Login w...

net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExportsBetweenSiblingAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)
  Run 1: RabbitMqTest.testExportsBetweenSiblingAgents:104 » AssumptionViolated got: <fa...
  Run 2: RabbitMqTest.cleanRabbitMq:61 » AuthenticationFailure ACCESS_REFUSED - Login w...

net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest.testExportsRequestsBetweenAgents(net.roboconf.messaging.internal.client.rabbitmq.RabbitMqTest)
  Run 1: RabbitMqTest.testExportsRequestsBetweenAgents:96 » AssumptionViolated got: <fa...
  Run 2: RabbitMqTest.cleanRabbitMq:61 » AuthenticationFailure ACCESS_REFUSED - Login w...



Tests run: 54, Failures: 0, Errors: 5, Skipped: 4
````

**Comment by vincent-zurczak** [comment]
Oops! I finally confirm this bug.
