### ISSUE TITLE
Restoration Issue

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#182]
Sometimes, exceptions appear in the DM's logs about restoration.

```
2015-01-22 17:09:49,038 | ERROR | .configuration]) | Manager                          | 57 - net.roboconf.dm - 0.2.0.SNAPSHOT | Cannot restore application in /tmp/roboconf-dm/applications/mongo-replicaset (I/O exception).
2015-01-22 17:09:49,039 | TRACE | .configuration]) | Manager                          | 53 - net.roboconf.core - 0.2.0.SNAPSHOT | java.io.IOException: The DM was not started.
	at net.roboconf.dm.management.Manager.__M_checkConfiguration(Manager.java:335)
	at net.roboconf.dm.management.Manager.checkConfiguration(Manager.java)
	at net.roboconf.dm.management.Manager.__M_loadNewApplication(Manager.java:439)
	at net.roboconf.dm.management.Manager.loadNewApplication(Manager.java)
	at net.roboconf.dm.management.Manager.__M_restoreApplications(Manager.java:879)
	at net.roboconf.dm.management.Manager.restoreApplications(Manager.java)
	at net.roboconf.dm.management.Manager.__M_reconfigure(Manager.java:235)
	at net.roboconf.dm.management.Manager.reconfigure(Manager.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.felix.ipojo.util.Callback.call(Callback.java:237)
	at org.apache.felix.ipojo.handlers.configuration.ConfigurationHandler.__M_notifyUpdated(ConfigurationHandler.java:686)
	at org.apache.felix.ipojo.handlers.configuration.ConfigurationHandler.notifyUpdated(ConfigurationHandler.java)
	at org.apache.felix.ipojo.handlers.configuration.ConfigurationHandler.__M_updated(ConfigurationHandler.java:769)
	at org.apache.felix.ipojo.handlers.configuration.ConfigurationHandler.updated(ConfigurationHandler.java)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:148)
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:81)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1448)
	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1404)
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:103)
	at java.lang.Thread.run(Thread.java:744)

2015-01-22 17:09:49,040 | INFO  | .configuration]) | Manager                          | 57 - net.roboconf.dm - 0.2.0.SNAPSHOT | The DM was successfully (re)configured.
2015-01-22 17:09:49,040 | WARN  |  pool-1-thread-1 | Manager                          | 57 - net.roboconf.dm - 0.2.0.SNAPSHOT | Invalid location for the configuration directory (empty or null). Switching to /home/gibello/OpenPAAS/roboconf/karaf/roboconf-karaf-dist-dm/target/assembly/data/tmp/roboconf-dm
```

**Comment by vincent-zurczak** [comment]
Restoration fails because the DM is most likely not configured correctly at the beginning.
The messaging should not throw an error at this moment. It should load the application first and then check the messaging.
