### ISSUE TITLE
Add a property to pass options to run Docker containers

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#335]
I'm writing a Roboconf application requiring a Tomcat cluster. My tomcat cluster is running on two docker containers where Tomcat is deployed using scripts.

I'm facing to the following problem: http://stackoverflow.com/questions/29683231/tomcat7-fail-to-start-inside-ubuntu-docker-container

Is it possible to add a new property to the target "Docker" to be able to set the right options when launching the Docker containers ?

        docker.user = roboconf
        docker.password = roboconf
        docker.endpoint = http://localhost:4243
    --> docker.option = --cap-add SYS_PTRACE
        docker.image = roboconf-tomcat8
        docker.agent.package = http://repo1.maven.org/maven2/net/roboconf/roboconf-karaf-dist-agent/0.3/roboconf-karaf-dist-agent-0.3.tar.gz
        docker.agent.jre-packages = tomcat8

**Comment by gibello** [comment]
A good idea.

As a possible workaround, it is possible to add it to DOCKER_OPTS in 
/etc/defaults/docker (but it would apply to all docker containers).

**Comment by cdeneux** [comment]
When using `docker.command.options = --cap-add SYS_PTRACE` or `docker.command.options = --cap-add=SYS_PTRACE`, I get the following error:

    2015-06-23 16:09:36,393 | DEBUG | DockerMachineConfigurator        | Creating image roboconf-tomcat8...
    2015-06-23 16:09:36,393 | DEBUG | DockerMachineConfigurator        | Creating a container from image roboconf-tomcat8...
    2015-06-23 16:09:36,394 | INFO  | DockerMachineConfigurator        | Creating container rbcf_2a78cecc-9f7f-4ade-a574-c066f7bd443d from image roboconf-tomcat8
    2015-06-23 16:09:36,654 | ERROR | edTargetHandler$CheckingRunnable | An error occurred while configuring machine 'rbcf_2a78cecc-9f7f-4ade-a574-c066f7bd443d'. com.github.dockerjava.api.InternalServerErrorException: Cannot start container 9c40283a5462b96a49041eb506748a313fee55c07d2e1f454a98ecb7e3c7ffe7: [8] System error: exec: "--cap-add=SYS_PTRACE": executable file not found in $PATH
    2015-06-23 16:09:36,654 | TRACE | edTargetHandler$CheckingRunnable | net.roboconf.target.api.TargetException: com.github.dockerjava.api.InternalServerErrorException: Cannot start container 9c40283a5462b96a49041eb506748a313fee55c07d2e1f454a98ecb7e3c7ffe7: [8] System error: exec: "--cap-add=SYS_PTRACE": executable file not found in $PATH
	    at net.roboconf.target.docker.internal.DockerMachineConfigurator.createContainer(DockerMachineConfigurator.java:188)
	    at net.roboconf.target.docker.internal.DockerMachineConfigurator.configure(DockerMachineConfigurator.java:126)
	    at net.roboconf.target.api.AbstractThreadedTargetHandler$CheckingRunnable.run(AbstractThreadedTargetHandler.java:180)
	    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	    at java.lang.Thread.run(Thread.java:745)
    Caused by: com.github.dockerjava.api.InternalServerErrorException: Cannot start container 9c40283a5462b96a49041eb506748a313fee55c07d2e1f454a98ecb7e3c7ffe7: [8] System error: exec: "--cap-add=SYS_PTRACE": executable file not found in $PATH
	    at com.github.dockerjava.core.util.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:54)
	    at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	    at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	    at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
	    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:667)
	    at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:664)
	    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:664)
	    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
	    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
	    at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:26)
	    at com.github.dockerjava.jaxrs.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	    at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:57)
	    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:29)
	    at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:302)
	    at net.roboconf.target.docker.internal.DockerMachineConfigurator.createContainer(DockerMachineConfigurator.java:181)
	    ... 9 more

**Comment by vincent-zurczak** [comment]
OK. We cannot pass options in the command like we would do in CLI mode.
These options must be passed programmatically to the REST client for Docker. This is because [Docker's REST API](https://docs.docker.com/reference/api/docker_remote_api/) expects a JSon object and not a raw command line. And building this object is handled by the REST client.

We have two options: by-pass or upgrade the REST client, but that's not easy, to build our JSon object differently. Or find a way to read options in our **target.properties** file and inject them programmatically. It is the option I chose. With Java reflection, I inject simple Docker options. Simple means their type: String, int, long, String[] and Capability[]. Other options are not supported at the moment. We will see with time if their support is requested.
