### ISSUE TITLE
Exception in autonomic tests

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#339]
Seen in the build.
For the record, it does not prevent the build from succeeding.

```
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in net.roboconf.dm.internal.autonomic.RulesParserTest
Running net.roboconf.dm.internal.autonomic.RuleBasedEventHandlerTest
Exception in thread "Roboconf's Management Timer" java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394)
	at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:405)
	at net.roboconf.dm.internal.tasks.CheckerMessagesTask.run(CheckerMessagesTask.java:72)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by vincent-zurczak** [comment]
What is most likely happening is that we go through the root instances of an application in one thread, and that we try to add a new root instance at the same moment in another thread. This exception is not seen everytime, it is really a random issue, but it highlights a design problem.

Root instances are handled by a LinkedHashSet for the moment, as well as other instances groups (parents, children). We could use a thread-safe set like [ConcurrentSkipListSet](http://docs.oracle.com/javase/6/docs/api/java/util/concurrent/ConcurrentSkipListSet.html) but we would loose insertion order.

Collections.synchronizedSet requires we wrap iterations (going through the set) with a synchronized block. Which will make the code worst...

Or we can also create a set from a ConcurrentHashMap with Collections utilities.
The **ConcurrentSkipListSet** will probably bring more predictability for tests, since natural ordering is considered, while a ConcurrentHashMap is basically a HashMap (random ordering).

WDT? :last_quarter_moon:

**Comment by vincent-zurczak** [comment]
CopyInWriteArray seems a valid alternative.
We perform much more read than write operations. The only exception is when we parse instances files. If we go with it, we should gather instances to add in a distinct collection, and add them all together in the set.
