### ISSUE TITLE
The parameter 'docker.agent.package' should be more user-friendly

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#341]
I'm upgrading my Roboconf application from version 0.3 to 0.4-SNAPSHOT. I have upgraded the version of `roboconf-maven-plugin` in my POM files. I must upgrade also the version of agent used in the target `docker` (the value of parameter `docker.agent.package`). As I have several different Docker containers, I must update the parameter for each. I think that it can be more user-friendly updating the value only once.

Is it possible to have a value generated dynamically:
* by the `roboconf-maven-plugin`, the value of `docker.agent.package` will be a a value generated from the `roboconf-maven-plugin` version,
* or at runtime using the version of the Roboconf DM.

**Comment by vincent-zurczak** [comment]
We do not need another parameter.
Just use the usual Maven properties.

In your POM...

```xml


In your target.properties...

```xml
docker.agent.package = http://repo1.maven.org/maven2/net/roboconf/roboconf-karaf-dist-dm/${project.version}/roboconf-karaf-dist-dm-${project.version}.tar.gz
```

If you switch to another release, then just updating

**Comment by cdeneux** [comment]
Ok, thanks. But it does not work with snapshot versions because the artifact `net.roboconf:roboconf-karaf-dist-dm` is timestamped. Using the value `0.4-SNAPSHOT` for the property `roboconf-version`, the following error occurs:

    2015-06-23 14:16:39,500 | DEBUG | DockerMachineConfigurator        | Creating image roboconf-tomcat8...
    2015-06-23 14:16:39,500 | INFO  | DockerMachineConfigurator        | Creating image roboconf-tomcat8 from a generated Dockerfile.
    2015-06-23 14:16:40,524 | ERROR | edTargetHandler$CheckingRunnable | An error occurred while configuring machine 'rbcf_eb0bd331-1724-4294-ab78-7c464940d5c2'. java.io.FileNotFoundException: https://oss.sonatype.org/content/repositories/snapshots/net/roboconf/roboconf-karaf-dist-agent/0.4-SNAPSHOT/roboconf-karaf-dist-agent-0.4-SNAPSHOT.tar.gz
    2015-06-23 14:16:40,525 | TRACE | edTargetHandler$CheckingRunnable | net.roboconf.target.api.TargetException: java.io.FileNotFoundException: https://oss.sonatype.org/content/repositories/snapshots/net/roboconf/roboconf-karaf-dist-agent/0.4-SNAPSHOT/roboconf-karaf-dist-agent-0.4-SNAPSHOT.tar.gz
	    at net.roboconf.target.docker.internal.DockerMachineConfigurator.createImage(DockerMachineConfigurator.java:235)
	    at net.roboconf.target.docker.internal.DockerMachineConfigurator.configure(DockerMachineConfigurator.java:119)
	    at net.roboconf.target.api.AbstractThreadedTargetHandler$CheckingRunnable.run(AbstractThreadedTargetHandler.java:180)
	    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	    at java.lang.Thread.run(Thread.java:745)
    Caused by: java.io.FileNotFoundException: https://oss.sonatype.org/content/repositories/snapshots/net/roboconf/roboconf-karaf-dist-agent/0.4-SNAPSHOT/roboconf-karaf-dist-agent-0.4-SNAPSHOT.tar.gz
	    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	    at net.roboconf.target.docker.internal.DockerfileGenerator.generateDockerfile(DockerfileGenerator.java:104)
	    at net.roboconf.target.docker.internal.DockerMachineConfigurator.createImage(DockerMachineConfigurator.java:217)
	... 9 more

We can use an explicit URL as `https://oss.sonatype.org/content/repositories/snapshots/net/roboconf/roboconf-karaf-dist-agent/0.4-SNAPSHOT/roboconf-karaf-dist-agent-0.4-20150622.161556-7.tar.gz` but this URL will be unavailable shortly when the Maven repository will purge its on snapshot iterations. And the Roboconf application source code should be changed.

**Comment by vincent-zurczak** [comment]
I don't see any other solution regarding snapshot verions.
No automatic solution seems affordable. Setting the URL by hand remains the best option.

**Comment by cdeneux** [comment]
Using the service API of Nexus (the Maven repository manager where Roboconf artifacts are deployed), I can retrieve the right timestamped archive from the version: `https://oss.sonatype.org/service/local/artifact/maven/redirect?g=net.roboconf&r=snapshots&a=roboconf-karaf-dist-agent&v=${roboconf.version}&p=zip`

In my mind the parameter `docker.agent.package` should have a default value:
* based on `docker.base.image` if exists, to be able to select the right agent according to operating system for example,
* based on the version of the Roboconf DM:
  * if the version of DM is released: `https://oss.sonatype.org/service/local/artifact/maven/redirect?r=releases&g=net.roboconf&a=roboconf-karaf-dist-agent&v=${roboconf.version}&p=zip`
  * if the version of DM is a snapshot version: `https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=net.roboconf&a=roboconf-karaf-dist-agent&v=${roboconf.version}&p=zip`
We will use the parameter `docker.agent.package` only when we want a specific version of the Roboconf agent.

**Comment by vincent-zurczak** [comment]
Rather than putting the **redirect** operation of Nexus, I think Roboconf should get the URL with the **resolve** one.

Example:

```
https://oss.sonatype.org/service/local/artifact/maven/resolve?r=snapshots&g=net.roboconf&a=roboconf-karaf-dist-agent&v=0.4-SNAPSHOT&p=zip
```

The **repositoryPath** property will give the local path to access the artifact.
We will thus be able to log it and inject it in the Dockefile.

And since there is no OS-based distribution, the **docker.base.image** is useless. Even if we have Debian packages since version 0.4, we always generate the Docker image from an archive (ZIP or TAR.GZ).

**Comment by vincent-zurczak** [comment]
OK. We can do that...
