### ISSUE TITLE
Error "Connexion refused" when using a Nexus API URL for 'docker.agent.package'

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#350]
When I set the following URL in the parameter `docker.agent.package`:

    https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=net.roboconf&a=roboconf-karaf-dist-agent&v=0.4-SNAPSHOT&p=zip

I get the following error:

    2015-06-25 09:48:32,875 | DEBUG | DockerMachineConfigurator        | Docker's output:
    {"stream":"Step 0 : FROM ubuntu:15.04\n"}
    {"stream":" ---\u003e 6be21d1e5d1e\n"}
    {"stream":"Step 1 : COPY redirect?r=snapshots\u0026g=net.roboconf\u0026a=roboconf-karaf-dist-agent\u0026v=0.4-SNAPSHOT\u0026p=zip /usr/local/\n"}
    2015-06-25 09:48:32,882 | ERROR | edTargetHandler$CheckingRunnable | An error occurred while configuring machine 'rbcf_22a959df-5407-4e06-967d-94a41ab003d6'. org.apache.http.conn.HttpHostConnectException: Connect to localhost:4243 [localhost/127.0.0.1] failed: Connexion refusée
    2015-06-25 09:48:32,883 | TRACE | edTargetHandler$CheckingRunnable | javax.ws.rs.ProcessingException: org.apache.http.conn.HttpHostConnectException: Connect to localhost:4243 [localhost/127.0.0.1] failed: Connexion refusée
	    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:513)
	    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
	    at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:705)
	    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:701)
	    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:417)
	    at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:313)
	    at com.github.dockerjava.jaxrs.ListImagesCmdExec.execute(ListImagesCmdExec.java:39)
	    at com.github.dockerjava.jaxrs.ListImagesCmdExec.execute(ListImagesCmdExec.java:17)
	    at com.github.dockerjava.jaxrs.AbstrDockerCmdExec.exec(AbstrDockerCmdExec.java:57)
	    at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:29)
	    at net.roboconf.target.docker.internal.DockerUtils.findImageByIdOrByTag(DockerUtils.java:129)
	    at net.roboconf.target.docker.internal.DockerMachineConfigurator.configure(DockerMachineConfigurator.java:127)
	    at net.roboconf.target.api.AbstractThreadedTargetHandler$CheckingRunnable.run(AbstractThreadedTargetHandler.java:224)
	    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	    at java.lang.Thread.run(Thread.java:745)
    Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:4243 [localhost/127.0.0.1] failed: Connexion refusée
	    at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:138)
	    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:357)
	    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:218)
	    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:465)
	    ... 23 more
    Caused by: java.net.ConnectException: Connexion refusée
	    at java.net.PlainSocketImpl.socketConnect(Native Method)
	    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	    at java.net.Socket.connect(Socket.java:579)
	    at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	    at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:118)
	    ... 32 more

**Comment by vincent-zurczak** [comment]
This is because the file name is not extracted correctly from the URL.

**Comment by cdeneux** [comment]
That works fine with my test with the last 0.4-SNAPSHOT (#9)
