### ISSUE TITLE
Unable to create messaging client

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#391]
With Roboconf 0.5-SNAPSHOT (#6), after several successful deployments, I'm not enable to do more.
I get an error about the RabbitMQ creation (The DM configuration is ok about messaging system):

    2015-07-09 15:48:28,780 | DEBUG | ManagementResource               | Request: load application from uploaded ZIP file (pvc-soa-app-sample-1.0.0-SNAPSHOT.zip).
    2015-07-09 15:48:29,150 | DEBUG | ManagementResource               | Request: load application from /home/cdeneux/roboconf-karaf-dist-dm-0.5-SNAPSHOT/data/tmp/roboconf/pvc-soa-app-sample-1.0.0-SNAPSHOT.
    2015-07-09 15:48:29,151 | WARN  | Manager                          | The DM's configuration is invalid. Please, review the messaging settings.
    2015-07-09 15:48:29,151 | ERROR | ManagementResource               | A new application template could not be loaded. The DM's configuration is invalid. Please, review the messaging settings.
    2015-07-09 15:48:29,152 | TRACE | ManagementResource               | java.io.IOException: The DM's configuration is invalid. Please, review the messaging settings.
	at net.roboconf.dm.management.Manager.__M_checkConfiguration(Manager.java:477)
	at net.roboconf.dm.management.Manager.checkConfiguration(Manager.java)
	at net.roboconf.dm.management.Manager.__M_loadApplicationTemplate(Manager.java:497)
	at net.roboconf.dm.management.Manager.loadApplicationTemplate(Manager.java)
	at net.roboconf.dm.rest.services.internal.resources.impl.ManagementResource.loadApplicationTemplate(ManagementResource.java:125)
	at net.roboconf.dm.rest.services.internal.resources.impl.ManagementResource.loadApplicationTemplate(ManagementResource.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:267)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

Before this exception, I have the following message in log file. I think that it should be logged with level ERROR or WARN, and the stack trace of the associated exception should be also logged:

    2015-07-09 15:47:49,841 | INFO  | DismissClientDm                  | No messaging client is available. Action is dismissed. Review the messaging configuration.

**Comment by vincent-zurczak** [comment]
The configuration directory was cleared. The DM was restarted. RabbitMQ was restarted.
And still, the DM was not able to connect with RMQ. RMQ's management console did not show any connection.

**Comment by cdeneux** [comment]
After re-installation of the DM, that works fine.

**Comment by vincent-zurczak** [comment]
I could not reproduce it. And it did not occur again since it was reported.
