### ISSUE TITLE
Docker does not run in Karaf anymore with Java 7

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#402]
The unit test about  running contains with additional packages remains stuck, it does not progress.
It was also reported (by @cdeneux) the same thing occurred with a real Karaf installation when deploying additional bundles in the agent.

The fact that the unit test does not succeed confirms there is something.
For the record, this test, as well as some others, are not run on our CI, as they require a Docker installation (and that Travis CI now uses Docker containers to run builds). Some, these tests are only run locally by developers.

**Comment by vincent-zurczak** [comment]
OK. It seems remaining stuck is a side effect of some of the tests, i.e. that we try to install alternate JRE... So, downloading takes time. A very long time when we have a **normal** internet connection. I will make these tests ignored by default. I will also add warning logs about it.

Anyway, I added unit tests about substitution of run parameters, and I think I found some bugs that I fixed. I am not sure these bugs were already encountered though.

**Comment by vincent-zurczak** [comment]
Still investigating what @cdneux reported.
I confirm that when we try to generate a new image (no matter if there are additional things or not), nothing happens. Roboconf logs report a machine is under configuration. However, there is no sign of a temporary container in Docker to create a new image.

Even worse, when undeploying everything in the console, the root instances remain in the **being deployed** state.

**Comment by vincent-zurczak** [comment]
Oh! Oh! :fearful: 
I found it in Karaf logs (not in roboconf.log)

```
2015-08-01 11:54:00,124 | ERROR | qtp486010236-87  | ContainerResponse                | 14 - com.sun.jersey.jersey-server - 1.18.2 | The exception contained within MappableContainerException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl
	at net.roboconf.target.docker.internal.DockerUtils.createDockerClient(DockerUtils.java:98)
	at net.roboconf.target.docker.internal.DockerHandler.__M_terminateMachine(DockerHandler.java:178)
	at net.roboconf.target.docker.internal.DockerHandler.terminateMachine(DockerHandler.java)
	at net.roboconf.dm.internal.delegates.InstanceMngrDelegate.undeployTarget(InstanceMngrDelegate.java:437)
	at net.roboconf.dm.internal.delegates.InstanceMngrDelegate.changeInstanceState(InstanceMngrDelegate.java:147)
	at net.roboconf.dm.internal.delegates.InstanceMngrDelegate.undeployAll(InstanceMngrDelegate.java:273)
	at net.roboconf.dm.management.Manager.__M_undeployAll(Manager.java:717)[21:net.roboconf.dm:0.5.0.SNAPSHOT]
	at net.roboconf.dm.management.Manager.undeployAll(Manager.java)[21:net.roboconf.dm:0.5.0.SNAPSHOT]
	at net.roboconf.dm.rest.services.internal.resources.impl.ApplicationResource.undeployAll(ApplicationResource.java:207)[27:net.roboconf.roboconf-dm-rest-services:0.5.0.SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_79]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)[14:com.sun.jersey.jersey-server:1.18.2]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)[14:com.sun.jersey.jersey-server:1.18.2]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)[14:com.sun.jersey.jersey-server:1.18.2]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)[14:com.sun.jersey.jersey-server:1.18.2]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)[14:com.sun.jersey.jersey-server:1.18.2]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)[15:com.sun.jersey.servlet:1.18.2]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)[15:com.sun.jersey.servlet:1.18.2]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)[15:com.sun.jersey.servlet:1.18.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)[17:javax.servlet-api:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)[82:org.eclipse.jetty.servlet:9.2.10.v20150310]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[82:org.eclipse.jetty.servlet:9.2.10.v20150310]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[102:org.ops4j.pax.web.pax-web-jetty:4.1.4]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[80:org.eclipse.jetty.security:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:267)[102:org.ops4j.pax.web.pax-web-jetty:4.1.4]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[82:org.eclipse.jetty.servlet:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[102:org.ops4j.pax.web.pax-web-jetty:4.1.4]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.Server.handle(Server.java:497)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)[73:org.eclipse.jetty.io:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[84:org.eclipse.jetty.util:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[84:org.eclipse.jetty.util:9.2.10.v20150310]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_79]
2015-08-01 11:54:00,134 | WARN  | qtp486010236-87  | ServletHandler                   | 84 - org.eclipse.jetty.util - 9.2.10.v20150310 | 
javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:420)[15:com.sun.jersey.servlet:1.18.2]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)[15:com.sun.jersey.servlet:1.18.2]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)[15:com.sun.jersey.servlet:1.18.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)[17:javax.servlet-api:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)[82:org.eclipse.jetty.servlet:9.2.10.v20150310]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)[82:org.eclipse.jetty.servlet:9.2.10.v20150310]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[102:org.ops4j.pax.web.pax-web-jetty:4.1.4]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)[80:org.eclipse.jetty.security:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:267)[102:org.ops4j.pax.web.pax-web-jetty:4.1.4]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)[82:org.eclipse.jetty.servlet:9.2.10.v20150310]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)[102:org.ops4j.pax.web.pax-web-jetty:4.1.4]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.Server.handle(Server.java:497)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)[81:org.eclipse.jetty.server:9.2.10.v20150310]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)[73:org.eclipse.jetty.io:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[84:org.eclipse.jetty.util:9.2.10.v20150310]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[84:org.eclipse.jetty.util:9.2.10.v20150310]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_79]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.github.dockerjava.jaxrs.DockerCmdExecFactoryImpl
	at net.roboconf.target.docker.internal.DockerUtils.createDockerClient(DockerUtils.java:98)
	at net.roboconf.target.docker.internal.DockerHandler.__M_terminateMachine(DockerHandler.java:178)
	at net.roboconf.target.docker.internal.DockerHandler.terminateMachine(DockerHandler.java)
	at net.roboconf.dm.internal.delegates.InstanceMngrDelegate.undeployTarget(InstanceMngrDelegate.java:437)
	at net.roboconf.dm.internal.delegates.InstanceMngrDelegate.changeInstanceState(InstanceMngrDelegate.java:147)
	at net.roboconf.dm.internal.delegates.InstanceMngrDelegate.undeployAll(InstanceMngrDelegate.java:273)
	at net.roboconf.dm.management.Manager.__M_undeployAll(Manager.java:717)[21:net.roboconf.dm:0.5.0.SNAPSHOT]
	at net.roboconf.dm.management.Manager.undeployAll(Manager.java)[21:net.roboconf.dm:0.5.0.SNAPSHOT]
	at net.roboconf.dm.rest.services.internal.resources.impl.ApplicationResource.undeployAll(ApplicationResource.java:207)[27:net.roboconf.roboconf-dm-rest-services:0.5.0.SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_79]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)[14:com.sun.jersey.jersey-server:1.18.2]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)[15:com.sun.jersey.servlet:1.18.2]
	... 24 more
```

**Comment by vincent-zurczak** [comment]
OK. I finally reverted part of the externalization of Docker dependencies.
Since almost every handler uses its own version of Jersey, let's keep "fat" jars.

I also fixed imported packages.
SLF4J was marked as provided in the POM, but the packages were not imported in the manifest. So, the logging classes were not found and the Docker client factory could not be instantiated.

**Comment by vincent-zurczak** [comment]
I renamed this issue so that it reflect the real issue.
