### ISSUE TITLE
Undeterministic tests

### ISSUE THREAD

**Issue by diarraa** [roboconf/roboconf-platform#456]
I got this error when I execute the command  '' mvn install " 
```
-------------------------------------------------------------------------------
Test set: net.roboconf.dm.internal.api.impl.TargetsMngrImplTest
-------------------------------------------------------------------------------
Tests run: 22, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.073 sec <<< FAILURE! - in net.roboconf.dm.internal.api.impl.TargetsMngrImplTest
testHints_noHint(net.roboconf.dm.internal.api.impl.TargetsMngrImplTest)  Time elapsed: 0.008 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<[1]> but was:<[2]>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at net.roboconf.dm.internal.api.impl.TargetsMngrImplTest.testHints_noHint(TargetsMngrImplTest.java:210)

testHints_hintOnApplication(net.roboconf.dm.internal.api.impl.TargetsMngrImplTest)  Time elapsed: 0.002 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<[1]> but was:<[2]>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at net.roboconf.dm.internal.api.impl.TargetsMngrImplTest.testHints_hintOnApplication(TargetsMngrImplTest.java:247)

testHints_hintOnApplicationTemplate(net.roboconf.dm.internal.api.impl.TargetsMngrImplTest)  Time elapsed: 0.003 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<[1]> but was:<[2]>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at net.roboconf.dm.internal.api.impl.TargetsMngrImplTest.testHints_hintOnApplicationTemplate(TargetsMngrImplTest.java:344)
 ``` 
Test files

**Comment by vincent-zurczak** [comment]
The resulting list is built by listing files.
It seems files are not listed the same way on every platform. The list should thus be sorted alphabetically.
