### ISSUE TITLE
Unknown protocol: mvn

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#487]
This issue is a partial following of #478.
Integration tests with inter-application bindings sometimes print the stack trace below.

```
Exception in thread "Roboconf Agent - Message Processor" java.lang.IllegalStateException: Unknown protocol: mvn
    at org.apache.felix.framework.URLHandlersStreamHandlerProxy.toExternalForm(URLHandlersStreamHandlerProxy.java:482)
    at org.apache.felix.framework.URLHandlersStreamHandlerProxy.toExternalForm(URLHandlersStreamHandlerProxy.java:474)
    at java.net.URL.toExternalForm(URL.java:921)
    at java.net.URL.toString(URL.java:907)
    at java.lang.ClassLoader.defineClassSourceLocation(ClassLoader.java:676)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:797)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.defineClass(BundleWiringImpl.java:2350)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.findClass(BundleWiringImpl.java:2134)
    at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1526)
    at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
    at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1998)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at net.roboconf.messaging.api.reconfigurables.ReconfigurableClientAgent.getDismissedClient(ReconfigurableClientAgent.java:87)
    at net.roboconf.messaging.api.reconfigurables.ReconfigurableClientAgent.getDismissedClient(ReconfigurableClientAgent.java:45)
    at net.roboconf.messaging.api.reconfigurables.ReconfigurableClient.getMessagingClient(ReconfigurableClient.java:303)
    at net.roboconf.messaging.api.reconfigurables.ReconfigurableClientAgent.sendMessageToTheDm(ReconfigurableClientAgent.java:165)
    at net.roboconf.agent.internal.lifecycle.AbstractLifeCycleManager.stopInstance(AbstractLifeCycleManager.java:388)
    at net.roboconf.agent.internal.lifecycle.AbstractLifeCycleManager.updateStateFromImports(AbstractLifeCycleManager.java:175)
    at net.roboconf.agent.internal.AgentMessageProcessor.processMsgRemoveImport(AgentMessageProcessor.java:516)
    at net.roboconf.agent.internal.AgentMessageProcessor.processMessage(AgentMessageProcessor.java:154)
    at net.roboconf.messaging.api.processors.AbstractMessageProcessor.run(AbstractMessageProcessor.java:110)
```

This does not prevent the tests from succeeding.
A discussion is in progress on the Karaf's users [mailing-list](http://mail-archives.apache.org/mod_mbox/karaf-user/201510.mbox/%3C561F5E41.7040406%40linagora.com%3E).

**Comment by vincent-zurczak** [comment]
It seems to occur only when using in-memory agents.
Maybe a race condition...

**Comment by vincent-zurczak** [comment]
Since #538, this error does not occur anymore.
In case it had to reappear, we would reopen this issue.
