### ISSUE TITLE
"Roboconf DM - Message Processor" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#489]
After a half day intensive usage, an OOM occurs on my DM

    Exception in thread "Roboconf DM - Message Processor" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2271)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
	at net.roboconf.core.utils.Utils.copyStream(Utils.java:231)
	at net.roboconf.core.utils.Utils.copyStream(Utils.java:284)
	at net.roboconf.core.utils.Utils.storeDirectoryResourcesAsBytes(Utils.java:517)
	at net.roboconf.core.utils.ResourceUtils.storeInstanceResources(ResourceUtils.java:67)
	at net.roboconf.dm.internal.api.impl.InstancesMngrImpl.changeInstanceState(InstancesMngrImpl.java:243)
	at net.roboconf.dm.internal.api.impl.InstancesMngrImpl.deployAndStartAll(InstancesMngrImpl.java:266)
	at net.roboconf.dm.internal.autonomic.RuleBasedEventHandler.createInstances(RuleBasedEventHandler.java:340)
	at net.roboconf.dm.internal.autonomic.RuleBasedEventHandler.handleEvent(RuleBasedEventHandler.java:140)
	at net.roboconf.dm.internal.environment.messaging.DmMessageProcessor.processMsgMonitoringEvent(DmMessageProcessor.java:289)
	at net.roboconf.dm.internal.environment.messaging.DmMessageProcessor.processMessage(DmMessageProcessor.java:99)
	at net.roboconf.messaging.api.processors.AbstractMessageProcessor.run(AbstractMessageProcessor.java:110)

**Comment by vincent-zurczak** [comment]
I will rever this last commit.
In fact, it seems we do not close an input stream when we copy file from a Maven repository.

We really need to make the `copyStream( InputStream, OutputStream )` private and replace it by a secured alternative.

**Comment by vincent-zurczak** [comment]
There was clearly a memory leak when getting the last information from Sonatype.
But there must be other leaks. I created #491. We will deal with it later.
