### ISSUE TITLE
Integration tests are not deterministic (and sometimes fail)

### ISSUE THREAD

**Issue by gibello** [roboconf/roboconf-platform#586]
Notably this one, but it is not exhaustive:

```
Running net.roboconf.integration.tests.paxrunner.miscellaneous.AgentTerminationTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.844 sec <<< FAILURE! - in net.roboconf.integration.tests.paxrunner.miscellaneous.AgentTerminationTest
run(net.roboconf.integration.tests.paxrunner.miscellaneous.AgentTerminationTest)  Time elapsed: 13.838 sec  <<< FAILURE!
java.lang.AssertionError: expected:<DEPLOYED_STARTED> but was:<DEPLOYED_STOPPED>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at net.roboconf.integration.tests.paxrunner.miscellaneous.AgentTerminationTest.run(AgentTerminationTest.java:129)
```

**Comment by vincent-zurczak** [comment]
Another error, mostly on Oracle JDK 8.

```
testExportsRequestsBetweenAgents(net.roboconf.messaging.http.internal.HttpMessagingTest)  Time elapsed: 1.064 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at net.roboconf.messaging.http.internal.HttpMessagingTest.testExportsRequestsBetweenAgents(HttpMessagingTest.java:129)
```

**Comment by vincent-zurczak** [comment]
And sometimes...

```
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.576 sec <<< FAILURE! - in net.roboconf.messaging.http.internal.HttpMessagingTest
testExportsRequestsBetweenAgents(net.roboconf.messaging.http.internal.HttpMessagingTest)  Time elapsed: 1.525 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at net.roboconf.messaging.http.internal.HttpMessagingTest.testExportsRequestsBetweenAgents(HttpMessagingTest.java:129)
```

**Comment by vincent-zurczak** [comment]
Most of the time, they pass on Java 7.
We often have issues with Java 8 and integration tests. I saw similar error reports on Karaf's mailing list when there are many integration tests.

And I am less and less patient with restarting builds. :rage: 
So, I suggest we keep integration tests running only for the build that manages code coverage and Maven uploads, that is to say OpenJDK 7. We do not need integration tests to run with other JDKs.
