### ISSUE TITLE
java.net.BindException in integration tests

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#666]
This exception seems to occur quite a number of times during integration tests.

```
java.net.BindException: Adresse déjà utilisée
	at sun.nio.ch.Net.bind0(Native Method)[:1.7.0_101]
	at sun.nio.ch.Net.bind(Net.java:463)[:1.7.0_101]
	at sun.nio.ch.Net.bind(Net.java:455)[:1.7.0_101]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)[:1.7.0_101]
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)[:1.7.0_101]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerImpl$1.start(JettyServerImpl.java:281)
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:221)
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:195)
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.registerServlet(HttpServiceStarted.java:179)
	at org.ops4j.pax.web.service.internal.HttpServiceProxy.registerServlet(HttpServiceProxy.java:64)
	at org.osgi.service.http.HttpService$$Proxy.registerServlet(Unknown Source)
	at net.roboconf.dm.rest.services.internal.ServletRegistrationComponent.__M_starting(ServletRegistrationComponent.java:102)
	at net.roboconf.dm.rest.services.internal.ServletRegistrationComponent.starting(ServletRegistrationComponent.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.7.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)[:1.7.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_101]
...
```

Looking at the stack trace, we can see one our iPojo component is responsible.
We should verify a path is not already used when registering a servlet.

**Comment by vincent-zurczak** [comment]
http://servicemix.396122.n5.nabble.com/java-net-BindException-Address-already-in-use-connect-td5722928.html

So, it may also be an issue with the OS that takes time to reuse an existing socket.

**Comment by vincent-zurczak** [comment]
Maybe we could catch these bind exceptions and apply a retry policy in our start method.

**Comment by vincent-zurczak** [comment]
OK. I found a better solution, as it is only about itnegration tests.
For every test that involves the DM, we change the port of Jetty. And thus, there is no more conflict when we register our servlets.
