### ISSUE TITLE
Web socket: skip timeouts on read

### ISSUE THREAD

**Issue by vincent-zurczak** [roboconf/roboconf-platform#730]
Letting a JS web socket idle too long results in the following error in the DM's logs.

```
2016-11-30 20:04:13,223 | TRACE | tp1805304172-129 | RoboconfWebSocket                | 23 - net.roboconf.core - 0.8.0.SNAPSHOT | java.lang.Exception: java.net.SocketTimeoutException: Timeout on Read
	at net.roboconf.dm.rest.services.internal.websocket.RoboconfWebSocket.onWebSocketError(RoboconfWebSocket.java:60)
	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onError(JettyListenerEventDriver.java:93)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingError(AbstractEventDriver.java:95)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingError(WebSocketSession.java:296)
	at org.eclipse.jetty.websocket.common.WebSocketSession.notifyError(WebSocketSession.java:347)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:545)
	at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:173)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:510)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback$1.run(AbstractConnection.java:586)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketTimeoutException: Timeout on Read
	... 7 more
```

The web socket in the DM does not expect any data.
So, we should set the read timeout to -1.

**Comment by vincent-zurczak** [comment]
For the record, read timeouts are not the same than connection timeouts.
